### ISSUE TITLE
Pre Trained 모델 사용 관련 질문 

### ISSUE THREAD

**Issue by developer0hye** [Korea-Health-Datathon/KHD2020#10]
안녕하세요.

참가팀 의전봇의  권용혜입니다.

https://github.com/khd2019/khd2019/issues/14 를 읽고  Pre Trained 모델 사용 관련하여 질문이 있습니다.

(불가) 외부 데이터(ImageNet, MIAS Mammography 등) 및 백본(네트워크) 사용 불가
(불가) imagenet-pretrained 백본 등 pretrained 모델 및 네트워크 사용 불가
(가능) scratch 형태로만 진행 가능 하며, 주어진 학습 데이터를 이용한 data augmentation 가능

위 조항에서 **scratch 형태로만 진행 가능하며**라는 부분은 모델 구조(vgg, resnet, densenet 등)는 기존에 연구된 네트워크 구조를 사용해도 되지만, 네트워크의 weight 는 random initialization 된 네트워크를 사용해야한다는 의미인가요?? 아니면 네트워크 구조 또한 기존에 연구된 네트워크 구조와 동일한(완전히) 구조는 사용할 수 없다는 의미인가요??

감사합니다.

**Comment by Korea-Health-Datathon** [comment]
안녕하세요, 
작년대회와 달리 올해는  pre trained model도 사용 가능하도록 규정이 바뀌어서
올해는 다른 제약사항이 없이 기존에 연구된 네트워크 구조도 사용 가능합니다.

**Comment by developer0hye** [comment]
@Korea-Health-Datathon 
감사합니다!
