### ISSUE TITLE
test관련 질문드립니다.

### ISSUE THREAD

**Issue by ssjx10** [Korea-Health-Datathon/KHD2020#107]
bind_model()의 infer() 부분에서 test data를 load하는데 이때 test data를 augmentation해서 inference를 해도 되나요?

**Comment by Leejuhui** [comment]
안녕하세요.

train data는 자유롭게 사용하셔도 되지만 test data는 다른 팀과 같은 조건의 결과를 비교해야하기 때문에 augmentation은 하지 않으셔야합니다.

다만, sample code 같이 전처리 과정은 추가하셔도 됩니다.

**Comment by ssjx10** [comment]
@Leejuhui 답변감사드립니다.
test data에서 augmentation을 하지 말라고 하셨는데 pretraind model마다 input size가  다릅니다. 
그래서 저희가 model에 넣기위해 input size를 resize해주는데 그 부분도 건들지 말아야 하나요?
아니면 resize까지는 가능한가요?

**Comment by Leejuhui** [comment]
Resize는 이미지 전처리로 구분되며 가능합니다.

말씀 드린 augmentation의 의미는 통상적으로 알려진 데이터 (flip, shear, zoom 등을 통한) 증대 등을 의미합니다.
![SmartSelect_20200924-131018_Samsung Internet](https://user-images.githubusercontent.com/32740524/94100013-55a22e00-fe67-11ea-895f-ecd853d06c52.jpg)
