### ISSUE TITLE
nsml login error

### ISSUE THREAD

**Issue by suheey** [Korea-Health-Datathon/KHD2020#11]
nsml login 시도 시, 다음과 같은 문제가 발생합니다. 

time="2020/09/21 11:59:30.249" level=info msg="please check your network connectivity by using 'ping ai-cli.nsml.navercorp.com' and 'telnet ai-cli.nsml.navercorp.com 443'"
time="2020/09/21 11:59:30.256" level=fatal msg="could not execute login: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 210.89.187.57:443: connectex: An attempt was made to access a socket in a way forbidden by its access permissions.\""

**Comment by Korea-Health-Datathon** [comment]
안녕하세요,

방화벽을 해제하신 후 로그인해보시기 바랍니다.
