### ISSUE TITLE
cv2 import error 

### ISSUE THREAD

**Issue by engrussman** [Korea-Health-Datathon/KHD2020#114]
Facing error while importing cv2. 

NSML Log start!
Traceback (most recent call last):
  File "main_deepDense.py", line 2, in <module>
    import cv2
ImportError: No module named 'cv2'
User session exited

**Comment by gibiee** [comment]
Did you install opencv?
You must input `opencv-python-headless` to array named install_requires in setup.py

**Comment by engrussman** [comment]
Thanks, It was fixed by putting the setup.py in the directory.
