### ISSUE TITLE
[submit error]RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.

### ISSUE THREAD

**Issue by curieuxjy** [Korea-Health-Datathon/KHD2020#117]
```
.......
Building docker image. It may take a while
.......KHD019/2020KHD_PNS/311: Session ready
KHD019/2020KHD_PNS/311: Load model
load nsml model takes 1.066556453704834 seconds
.Infer test set. The inference should be completed within 3600 seconds.
.Error occurred while inference. You can check error 'nsml submit --test'
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.

Infer test set takes 1.6466379165649414 seconds
..Error: Fail to get prediction result: KHD019/2020KHD_PNS/283/19
time="2020/09/25 10:11:19.607" level=fatal msg="Internal server error"
```

학습된 모델이 있는데 제출하니 위와 같은 error가 납니다. 
학습은 잘 되었는데 제출에서 오류가 날 수도 있나요..?
어떻게 디버깅 해야 할 지 몰라 질문 드립니다.

그리고 디버깅하고 난 후에 다시 training부터 다시 해야 하는지 문의드립니다.

**Comment by gibiee** [comment]
error에 대한 원인은 모르겠습니다만, 처음부터 training 하실 필요는 없을 것 같습니다.

공식문서 참고하시길 바랍니다.
https://n-clair.github.io/ai-docs/_build/html/ko_KR/contents/load_model.html

그리고 `nsml submit -t`를 사용해서 디버깅해보시기 바랍니다.

**Comment by curieuxjy** [comment]
대회 하시느라 바쁘 실텐데 답변 감사합니다! 👍 
구글링으로 관련 이슈 보았을 때는 input에 `.contiguous()`를 붙이라고 나와있어서.. 
그러면 load한 후 한번이라도 epoch을 돌려서 submit해야 할까요...?
아래 관련 이슈 링크입니다.
https://github.com/pytorch/pytorch/issues/32395

**Comment by gibiee** [comment]
사실 제가 pytorch를 써본적이 없어서 `.contiguous()`에 대한 이슈는 잘 모르겠습니다.

제가 `nsml.load()`를 테스트해봤을 때는 모델이 로드되어 세션에 저장되는 것은 가능했으나, 그 모델을 이어서 학습하는 것은 에러가 출력되었습니다.

따라서 코드 자체에 문제가 있는 경우에는 처음부터 training을 해야할 수도 있습니다.

공식문서에 나온대로, load -> save -> exit 식으로 실행하시고 `nsml model ls [세션이름]`으로 모델이 정상적으로 load되었는지 확인할 수 있습니다.
