### ISSUE TITLE
B track github 링크 문의

### ISSUE THREAD

**Issue by BbChip0103** [Korea-Health-Datathon/KHD2020#14]
안녕하세요. 아까 줌에서 채팅으로 깃허브 링크를 주신 것 같은데 찾아보니까 안보이네요 ㅠㅠ
혹시 링크나 PPT 등을 어디서 확인할 수 있을까요??

**Comment by philip555** [comment]
아래 링크 확인 부탁드립니다 :) 

부비동 데이터 설명자료 : https://github.com/KYBiMIL/KHD_2020/blob/master/KHD_2020_PNS.pdf

KHD_2020 code(tf) : https://github.com/KYBiMIL/KHD_2020/tree/master/tf_keras

KHD_2020 code(pytorch) : https://github.com/KYBiMIL/KHD_2020/tree/master/pytorch

**Comment by philip555** [comment]
죄송합니다. 위는 부비동(A Track) 데이터 설명입니다. 

아래 링크 확인 부탁드립니다 :) 

https://github.com/nccaiteam/KHD_2020
