### ISSUE TITLE
NSML command 로그인 실패 문의

### ISSUE THREAD

**Issue by Jieun1203** [Korea-Health-Datathon/KHD2020#17]
![image](https://user-images.githubusercontent.com/56375897/93737041-08328080-fc1d-11ea-98fa-1f519b81893d.png)

안녕하세요!
NSML command창에서 로그인이 위와 같은 에러가 뜨면서 불가능한데, 어떻게 해결하면 좋을지 알려주시면 감사하겠습니다!
웹페이지에서는 정상 로그인 되고 있습니다.

**Comment by Korea-Health-Datathon** [comment]
방화벽 해제 후 로그인해보시기 바랍니다.

**Comment by Jieun1203** [comment]
![image](https://user-images.githubusercontent.com/56375897/93738170-11711c80-fc20-11ea-9ea4-8a5c488fd4d6.png)

방화벽 해제 후 컴퓨터 재 부팅하여 로그인 해보았지만 똑같은 에러가 발생합니다.
