### ISSUE TITLE
NSML 로그인 실패 문의

### ISSUE THREAD

**Issue by hyeinhyun** [Korea-Health-Datathon/KHD2020#18]
웹페이지 및 command 로그인 실패 문의 드립니다!

깃헙 아이디 : hyeinhyun
<img width="589" alt="스크린샷 2020-09-21 오후 3 17 43" src="https://user-images.githubusercontent.com/41287040/93737262-a888a500-fc1d-11ea-929d-aaeda440c866.png">

**Comment by Korea-Health-Datathon** [comment]
팀명과 성함을 알려주시기 바랍니다.

**Comment by hyeinhyun** [comment]
STbigbase / 현혜인 입니다

**Comment by Korea-Health-Datathon** [comment]
신청 시 기재하신 ID는 hyunhi1123 입니다.
현재 위 아이디로 등록되어 있습니다.

**Comment by hyeinhyun** [comment]
아이디 등록에 실수가 있었던것 같습니다. 해결방법이 있을까요?
깃헙아이디는 hyeinhyun입니다..

**Comment by Korea-Health-Datathon** [comment]
hyeinhyun로 수정해드렸습니다.

**Comment by hyeinhyun** [comment]
감사합니다 :)
