### ISSUE TITLE
로그인 문의

### ISSUE THREAD

**Issue by yt-oh96** [Korea-Health-Datathon/KHD2020#21]
<img width="568" alt="스크린샷 2020-09-21 오후 3 28 49" src="https://user-images.githubusercontent.com/33571876/93737863-331dd400-fc1f-11ea-9a3f-1213a565e051.png">

어떻게 해야하나요?

**Comment by Korea-Health-Datathon** [comment]
이전 버전의 클라이언트를 쓰신 경우 해당 오류가 발생합니다.
클라이언트 업데이트 하신 후 접속해보시기 바랍니다.
