### ISSUE TITLE
Rejected: not enough credit (balance: 0) GPU 할당 문제

### ISSUE THREAD

**Issue by jhkjhkim** [Korea-Health-Datathon/KHD2020#23]
nsml run -d hello_nsml 명령을 진행한 후에 아래와 같은 오류가 발생합니다.

Rejected: not enough credit (balance: 0)
Since cluster does not have enough computing resources, job has been aborted. Please retry later
Error: No machine available that meets ALL your request such as CPU, RAM, Disk, GPU or its driver version
time="2020/09/21 15:33:23.056" level=fatal msg="Internal server error"

해결 방법을 알 수 있을까요?
감사합니다.

**Comment by yharam00** [comment]
저도 똑같이 나와요

**Comment by gywns6287** [comment]
저도 같습니다.

**Comment by suheey** [comment]
저도 똑같이 나옵니다. GPU 할당이 잘 된건가요??

**Comment by Korea-Health-Datathon** [comment]
추가 Credit 부여 완료되었습니다.
본 이슈는 클로징하도록 하겠습니다.
