### ISSUE TITLE
NSML Command 로그인 실패(ID: developer0hye) 문의

### ISSUE THREAD

**Issue by developer0hye** [Korea-Health-Datathon/KHD2020#24]
![image](https://user-images.githubusercontent.com/35001605/93738266-54cb8b00-fc20-11ea-9ca5-111a102d4be8.png)

NSML 로그인이 되지 않습니다. 확인부탁드립니다.

아이디는 developer0hye 입니다. 이전에 동일 이슈를 게시하였는데 답글이 올라오지 않아 다시 업로드 합니다!

웹에서는 로그인이 됩니다.

감사합니다.

**Comment by developer0hye** [comment]
웹에서는 로그인이 됩니다.

**Comment by philip555** [comment]
현재 NSML 상에 "developer0hye"은 등록된 아이디로 확인이 됩니다. 

다시 한번 시도 부탁드립니다. 
감사합니다.

**Comment by developer0hye** [comment]
@philip555 

다시 시도하였으나 접속이 되지 않습니다. 오류 내용은 아래와 같습니다.

![image](https://user-images.githubusercontent.com/35001605/93741429-5ea4bc80-fc27-11ea-9104-997882382801.png)

**Comment by wnsdud81684** [comment]
"developer0hye" 계정 재등록 하였습니다.

다시 한번 시도 부탁드립니다.
감사합니다.

**Comment by developer0hye** [comment]
@wnsdud81684 
확인 감사드립니다. 해결되었습니다.
