### ISSUE TITLE
Error: No machine available that meets ALL your request such as CPU, RAM, Disk, GPU or its driver version time="2020/09/21 15:48:09.903" level=fatal msg="Internal server error"

### ISSUE THREAD

**Issue by gywns6287** [Korea-Health-Datathon/KHD2020#25]
nsml run -d  Breast_Pathology
로 모델 실행 시 

Error: No machine available that meets ALL your request such as CPU, RAM, Disk, GPU or its driver version
time="2020/09/21 15:48:09.903" level=fatal msg="Internal server error"
에러가 발생합니다.

따로 할당 GPU 등을 설정해야하는 부분이 있는건지 문의 드립니다.

**Comment by Korea-Health-Datathon** [comment]
nsml에서 준비한 모든 GPU 자원을 사용 중일 때 발생하는 메시지입니다. 
주로 참가자가 몰리는 시간에 발생하는 경향이 있습니다. 다른 참가자의 session이 종료되면 다시 사용가능하게 되므로 보통은 10-20분 정도 후에 재실행하면 됩니다.

**Comment by jhkjhkim** [comment]
GPU가 총 50개가 안되는 건가요? 계속 똑같은 에러를 받고 있습니다..

**Comment by JOOCHANN** [comment]
저도 계속 똑같은 에러를 받고있습니다.
총 gpu resource가 56개인데 어느팀이 두개를 할당해 사용하여 다른팀이 사용 못하는것 같습니다

**Comment by justHungryMan** [comment]
@Korea-Health-Datathon nsml 아이디에 credit 이 부여되지 않아서 resource 를 점유할 수가 없습니다.

참가자들의 ID 에 credit 부여 부탁드립니다.

**Comment by Korea-Health-Datathon** [comment]
(16:30 기준) credit 추가 설정 되었습니다.
