### ISSUE TITLE
NSML Command 로그인 실패(ID: Joylish) 문의

### ISSUE THREAD

**Issue by Joylish** [Korea-Health-Datathon/KHD2020#26]
![image](https://user-images.githubusercontent.com/52230415/93738886-dff95080-fc21-11ea-909a-e8da57285bb7.png)
NSML 로그인이 되지 않습니다. sli.do에도 올렸지만 이슈에 올립니다. 확인부탁드립니다.

**Comment by Korea-Health-Datathon** [comment]
신청 시에는 joylish로 등록하신 것으로 확인되었습니다.
현재 nsml에 joylish로 계정 등록된 상태입니다.

**Comment by Joylish** [comment]
Joylish로 수정해주실 수 있을까요, 우선 정정 메일 보냈습니다.

**Comment by Joylish** [comment]
> 신청 시에는 joylish로 등록하신 것으로 확인되었습니다.
> 현재 nsml에 joylish로 계정 등록된 상태입니다.

Joylish로 수정해주실 수 있을까요, 우선 정정 메일 보냈습니다.

**Comment by philip555** [comment]
조금 전 수정했습니다. 

재 로그인 부탁드립니다.

**Comment by Joylish** [comment]
> 조금 전 수정했습니다.
> 
> 재 로그인 부탁드립니다.

감사합니다!
