### ISSUE TITLE
지원서 Github commit log 관련해서 문의드립니다.

### ISSUE THREAD

**Issue by CoodingPenguin** [Korea-Health-Datathon/KHD2020#3]
안녕하세요. 현재 지원서를 작성 중인데 **Github commit log**가 정확히 어느 것을 말하는 건지 궁금해서 문의드립니다. 

팀원들의 통합 commit 개수를 합해서 구하려 하는데 아래 이미지의 빨간색 부분을 합산해서 적으면되나요?

<img width="257" alt="캡처" src="https://user-images.githubusercontent.com/37505775/92747297-0536c500-f3bf-11ea-9b27-af23ad615b3b.PNG">

**Comment by Korea-Health-Datathon** [comment]
안녕하세요,
문의하신 내용에 대해 답변드립니다.

문의하신 "팀의 Github commit log (팀원 전체 합산)"는 팀원 각자 github를 통해 개발한 프로젝트의
commit 숫자를 모두 합산한 수치를 적어주시면 되는데요.

github commit log는 다음과 같은 방법으로 확인 가능합니다.

1. github 히스토리 항목

아래 그림과 같이 팀원들이 깃허브 히스토리 항목에서 커밋 수를 확인하여 합산
![image](https://user-images.githubusercontent.com/70007451/92766140-ea6d4c00-f3d0-11ea-9949-8b6a6720d67c.png)


2. git log 명령어 이용

git log --pretty=oneline | find /c /v ""
(리눅스인 경우 find 대신에 wc -l 를 사용하시면 됩니다)

![image](https://user-images.githubusercontent.com/70007451/92766310-0e309200-f3d1-11ea-8663-4f924dcac500.png)

위의 방법 중 편하신 방법을 통해 Github commit log 숫자를 적어주시면 됩니다.
팀원이 여러 명인 경우, 각자 commit log 숫자를 확인하신 후 전체 합을 적어주시면 됩니다.

감사합니다.

**Comment by CoodingPenguin** [comment]
답변 감사드립니다! 

답변을 정리하자면 "현재 제 Github에 있는 모든 레포의 Commit Log를 합산"하라는 말씀이신가요? 
또한 **프로젝트의 Commit Log**라고 하셨는데 단순 레포가 아니라 실 프로젝트 위주의 레포만을 말씀하시는 건가요? 여기서의 프로젝트의 정의가 궁금합니다!

감사합니다.

**Comment by Korea-Health-Datathon** [comment]
아래와 같이 계산하셔서 적어주시면 됩니다.

_commit log = 자신의 repository에서의 commit 수 + 본인이 참여한 다른 프로젝트에서 본인의 commit 수_

즉, 자신의 repo와 (타 프로젝트에 참여한 경우) 타 프로젝트를 별도로 구분하지는 않으나
**자신이 직접 commit한 수**만 적어주시면 됩니다

**Comment by CoodingPenguin** [comment]
이해됐습니다. 감사합니다!
