### ISSUE TITLE
GPU 사용

### ISSUE THREAD

**Issue by hyeinhyun** [Korea-Health-Datathon/KHD2020#30]
세션 진행시, credit =0이라고 뜹니다.
어떻게 해결해야할까요?
<img width="847" alt="스크린샷 2020-09-21 오후 4 20 33" src="https://user-images.githubusercontent.com/41287040/93741022-9d864280-fc26-11ea-831a-25e9c58abcab.png">

**Comment by kyuheejo** [comment]
저도 같은 에러가 뜨는데, nsml 홈페이지를 확인하면 GPU를 모두 사용중이라고 나옵니다. 다른 팀에서 사용하고 있는건가요?

**Comment by Korea-Health-Datathon** [comment]
전체 참가자들에 대해 추가 Credit 부여 완료되었습니다.
