### ISSUE TITLE
Session 진행 후 삭제 

### ISSUE THREAD

**Issue by skkuej** [Korea-Health-Datathon/KHD2020#32]
session 진행 후 NSML 페이지에서 진행을 확인하고 페이지 상에서 삭제 했는데
아래와 같이 GPU가 계속 할당 되어있는 것 같은 오류가 발생합니다. 

확인 부탁드립니다.

![image](https://user-images.githubusercontent.com/67458524/93742694-872db600-fc29-11ea-97c0-55f4739d1493.png)

**Comment by azzyjk** [comment]
nsml ps로 확인하신 후에 nsml rm 명령어로 삭제하시면 됩니다. :)
