### ISSUE TITLE
로그인 문의 입니다.

### ISSUE THREAD

**Issue by kongjeongbae** [Korea-Health-Datathon/KHD2020#33]
Team Namsan
kongjeongbae 입니다. (모두 소문자)
path를 등록했는데도 nsml login 시 github id 입력 조차 안뜨네요. 어떻게 해결해야할까요??
![image](https://user-images.githubusercontent.com/43724189/93743313-d0cad080-fc2a-11ea-8845-c66fec9b2952.png)

**Comment by taeseug** [comment]
수정했습니다. 다시한번 시도해 주세요

**Comment by wnsdud81684** [comment]
수정 하였습니다.

다시 한번 시도 부탁드립니다.
감사합니다.

**Comment by Korea-Health-Datathon** [comment]
이후에도 같은 현상이 지속될 경우, cli를 삭제하신 후 재설치 해보시기 바랍니다.

1) https://ai.nsml.navercorp.com/ 에 로그인 되는지 확인 
2) https://ai.nsml.navercorp.com/download 에서 cli 다시 다운 로드 후 로그인 시도

**Comment by kongjeongbae** [comment]
웹 상에서는 로그인이 됩니다.
cli 다시 다운로드했는데도 안됩니다.
방화벽도 다 해제했고, 네트워크도 바꿔서 시도하는데도 로그인이 아직 안되네요. github 아이디 입력 자체가 안뜹니다.

**Comment by Korea-Health-Datathon** [comment]
사용 중인 OS 정보와 실행 화면 전체의 스크린샷을 첨부해주시겠어요?

**Comment by kongjeongbae** [comment]
윈도우10 입니다.
![image](https://user-images.githubusercontent.com/43724189/93747282-6ec19980-fc31-11ea-9c14-bd6564e4a0e3.png)

**Comment by Korea-Health-Datathon** [comment]
기본 cmd에서 실행하시기 바랍니다.

**Comment by kongjeongbae** [comment]
감사합니다.
