### ISSUE TITLE
Session 생성 오류

### ISSUE THREAD

**Issue by donny8** [Korea-Health-Datathon/KHD2020#34]
Building docker image. It may take a while

해당 문구가 뜨면서 일단 계속 기다리고 있는데 원래 이렇게 오래 걸리는건 지 여쭤보고 싶습니다
계속 기다리면 될까요?
GUI 상으로는 "Allocating!" 만 뜨고 있습니다.
![image](https://user-images.githubusercontent.com/55653250/93743437-05d72300-fc2b-11ea-9afd-6b836d08b080.png)

**Comment by Korea-Health-Datathon** [comment]
세션 생성 시 환경 셋팅 때문에 docker image를 받아오고 빌드하는 과정에서 
docker image build에 시간이 소요되어 세션 생성이 지연될 수 있습니다.

이후부터는 동일 GPU에 docker image를 빌드하게 되면 빠르게 세션이 생성이 가능합니다.
