### ISSUE TITLE
제공된 코드 상에서 Train/Val accuracy 구하는 부분 수정 가능 여부 문이,

### ISSUE THREAD

**Issue by dahyedahye** [Korea-Health-Datathon/KHD2020#35]
안녕하세요,
혹시 제공해주신 코드 상에서 Train/Val accuracy 구하는 부분을 수정하는 것이 허용되는지 문의 드립니다.
감사합니다!

**Comment by gusdkgusdk** [comment]
혹시 어떤 트랙이신가요?

**Comment by dahyedahye** [comment]
부비동 트랙입니다!

**Comment by Leejuhui** [comment]
(main_*.py)에서  학습 결과의 nsml report만 가능하도록 변경하셔도 됩니다.

https://n-clair.github.io/vision-docs/_build/html/ko_KR/contents/nsml_library/nsml_report.html
