### ISSUE TITLE
세션 allocating이 50분째 나오고 있는중입니다.

### ISSUE THREAD

**Issue by dudwns511** [Korea-Health-Datathon/KHD2020#36]
세션이 강제 종료 되지도 않습니다.
어떻게 해결할 수 있을까요?

**Comment by taeseug** [comment]
nsml rm  session-id 하시면 삭제 하실 수 있습니다

**Comment by dudwns511** [comment]
msg="You cannot use this command for the other's session" 이렇게뜹니다

**Comment by wnsdud81684** [comment]
세션 아이디를 알려주시면 확인해보겠습니다.

감사합니다.

**Comment by redleaf-kim** [comment]
강제 삭제는 
`nsml rm -f 세션이름`

하시면 되요.

**Comment by dudwns511** [comment]
강제종료도 안되고 KHD012/PNS5/1 세션아이디입니다

**Comment by wnsdud81684** [comment]
세션 확인 후 강제종료 시켰습니다.

다시 한번 시도해주시면 감사하겠습니다.

**Comment by dudwns511** [comment]
지워주신거 확인했습니다.

감사합니다.
