### ISSUE TITLE
Session Allocated 상태에서 멈춰있습니다.

### ISSUE THREAD

**Issue by hongym7** [Korea-Health-Datathon/KHD2020#40]
command 에서 Run 수행 후, 바로 종료하였는데, 
Session Allocated 상태에서 지속적으러 멈춰있습니다.
추가 Run을 할 수 없는 상황이네요

Session 정보 : KHD004/Breast_Pathology/3

**Comment by ramyunnim** [comment]
nsml rm -f 세션명

하시면 됩니다
