### ISSUE TITLE
Session 관리 관련

### ISSUE THREAD

**Issue by HyeonhoonLee** [Korea-Health-Datathon/KHD2020#41]
웹 IDE를 실행하다가 갑자기중단되어서, 새로 model run을 하였더니,
현재 Session이 할당되어 gpu를 사용하고 있다고합니다.
웹상에서 session을 보면 계속 allocate한다고해서 중단을 눌러도 failed가 됩니다.
Session을 통째로 삭제하거나 나가는 방법은 없나요?

**Comment by redleaf-kim** [comment]
`nsml rm -f 세선이름`

하시면 세선 강제 삭제가 됩니다.
