### ISSUE TITLE
Session 강제 종료

### ISSUE THREAD

**Issue by dg-nam** [Korea-Health-Datathon/KHD2020#42]
allocating이 끝난뒤에 running을 하여도 터미널에서 세션이름 is already removed 메세지와 함께 nsml에서는 
Usage: nsml logs [OPTIONS] SESSION

Error: Invalid value for "SESSION": No valid sessions
메세지가 나오면서 running이 되지 않습니다 어떤점이 문제인지 알 수 있을까요

**Comment by Korea-Health-Datathon** [comment]
세션명을 기재해주시면 running 중인지 세션 삭제가 완료되었는지 확인해드리겠습니다.

**Comment by dohwankwak** [comment]
저희도 같은 에러인데 저희 세션도 확인부탁드립니다.
세션명은 KHD035/Breast_Pathology/17입니다.
@Korea-Health-Datathon

**Comment by Korea-Health-Datathon** [comment]
KHD035/Breast_Pathology/17 세션은 2020-09-21 21:31:18에 생성되었고
현재 삭제완료된 상태입니다.
