### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by Jasonlee1995** [Korea-Health-Datathon/KHD2020#45]
아이디 : Jasonlee1995

웹/cli에서 모두 접속이 불가능합니다.

불가능한 이유에는 not registered user라고 나옵니다.

확인 부탁드리겠습니다.

**Comment by kdh4672** [comment]
저는 웹은 들어가지는데, 저도 terminal에선 로그인이 안되네요..

**Comment by Korea-Health-Datathon** [comment]
신청서 확인 결과 jasonlee1995로 기재하신 것으로 확인되어 
수정해드렸습니다.
