### ISSUE TITLE
Cli Login Issue

### ISSUE THREAD

**Issue by kdh4672** [Korea-Health-Datathon/KHD2020#46]
![nsml_error](https://user-images.githubusercontent.com/54311546/93762655-f49e0e80-fc4a-11ea-97a2-0d9a3dff689b.png)

![github_capture](https://user-images.githubusercontent.com/54311546/93762860-50689780-fc4b-11ea-9bc9-4dbad3bb4b44.png)

![nsml_homepage_capture](https://user-images.githubusercontent.com/54311546/93762866-52325b00-fc4b-11ea-8ecf-db88ec7c341a.png)

nsml 홈페이지 로그인은 되는데, 보시다시피 cli에선 로그인이 안됩니다.
저희팀명은 HN이고 저희팀 3명 다 로그인이 안되고 있습니다.

**Comment by Korea-Health-Datathon** [comment]
nsml에서 지원하지 않는 쉘을 사용중인 것으로 보여집니다.
기본 cmd로 접속해보시기 바랍니다.

**Comment by kdh4672** [comment]
압축풀었던 파일들을 전부 지우고, 다시 설치했더니 되었습니다.
명령어는 같게 한 거 같아서 처음에 안되었던 원인은 모르겠습니다....

저희는
tar -zxvf nsml_client.linux.amd64.hack.tar.gz
export PATH=$PATH:/home/[user]
했더니 되었습니다. 감사합니다.
