### ISSUE TITLE
부비동 데이터셋 라벨 질문드립니다.

### ISSUE THREAD

**Issue by westhyena** [Korea-Health-Datathon/KHD2020#48]
한 이미지에 좌/우 라벨이 동시에 존재하는데,
샘플 코드를 보면 좌/우를 반으로 나누어서 따로따로 학습하도록 구현이 되어 있는 것 같습니다.

테스트 데이터셋도 좌/우로 나뉘어진 상태로 입력되어 각각의 라벨링을 맞추게 되나요?

**Comment by Leejuhui** [comment]
네, 맞습니다.
아래 링크에서 LoadTestData 함수 참고하시면 좋을 것 같습니다.

https://github.com/KYBiMIL/KHD_2020/blob/master/evaluation/data_loader.py

**Comment by westhyena** [comment]
감사합니다
