### ISSUE TITLE
run 중 강제중단 시 계속 allocating 하여 다음 세션을 열지 못하는 문제

### ISSUE THREAD

**Issue by MiSeon23** [Korea-Health-Datathon/KHD2020#58]
run 중 강제중단 시 계속 allocating 중이라며 stop으로 중단도 안되고 삭제도 되지 않습니다.

혹시 강제로 중단시켜주실 수 있으신가요?

KHD037/Breast_Pathology/23 입니다.

**Comment by wnsdud81684** [comment]
KHD037/Breast_Pathology/23 강제 중단 시켰습니다.

다시 한번 시도해주시길 바랍니다.
감사합니다.

**Comment by westhyena** [comment]
KHD007/PNS5/16
같은 현상이 발생합니다.
강제 중단 부탁드려요

실행 커맨드 누르고 빠르게 컨트롤C 눌러서 취소했는데 stop, 삭제가 둘다 안됩니다.
