### ISSUE TITLE
session stop이 안됨

### ISSUE THREAD

**Issue by SteveJayH** [Korea-Health-Datathon/KHD2020#61]
실수로 데이터셋을 정하지 않고
``
nsml run -e main.py
``
로 해서 docker이미지를 생성하는 도중 Ctrl + C 로 취소하였는데,
NSML 웹사이트에서 세션이 생성되어 있고 Stop을 누르는데도, 
Your request has been failed.라고 뜨고 삭제가 되지 않네요.
이 때문에 새로 run을 해보고 싶어도 No machine available이라고 뜹니다.

NICA팀의 KHD044/None/4 라는 세션인데, 관리자님께서 혹시 stop하고 삭제해 주실 수 있나요?
그리고 이처럼 세션이 stop이 되지 않을 경우는 어떻게 해결해야 하나요?

감사합니다.

**Comment by taeseug** [comment]
nsml  rm session-id 하시면 삭제 됩니다. 요청해 주신대로 세션은 정지 삭제 하였습니다.

감사합니다

**Comment by taeseug** [comment]
#nsml rm session-id  명령을 이용해 세션 id를 이용해 삭제해 주셔야 합니다     
요청해 주신 세션은 삭제 완료하였습니다.

감사합니다

**Comment by wnsdud81684** [comment]
삭제 했습니다. 
세션이 stop되지 않을 경우는 nsml rm session id 를 해주시면 강제 종료됩니다.

감사합니다.

**Comment by SteveJayH** [comment]
감사합니다
