### ISSUE TITLE
학습이 종료되면 세션이 자동 삭제됩니다.

### ISSUE THREAD

**Issue by sungchul2** [Korea-Health-Datathon/KHD2020#63]
KHD017/2020KHD_PNS
확인부탁드립니다~

**Comment by taeseug** [comment]
실행 터미널에서 사용하신 실행 커멘더를 올려 주세요

**Comment by rlatjcj** [comment]
nsml run -d 2020KHD_PNS -i -a "--augment custom --backbone resnet50 --weights imagenet --epochs 1 --step 1000  --standardize norm --flip --heq --noise 0.01 --rotate 20 --gamma 0.2 --translate 25 --keep_ratio --batch_size 8 --gpus 0 --evaluate"

**Comment by taeseug** [comment]
-i 를 빼고 한번 실행해 보세요 
감사합니다

**Comment by sungchul2** [comment]
감사합니다
