### ISSUE TITLE
nsml run pytorch docker image 사용시 안됩니다.

### ISSUE THREAD

**Issue by essemfly** [Korea-Health-Datathon/KHD2020#68]
기존에 주어주신 파일로

nsml run -e main_pytorch.py -d 2020KHD_PNS 로 실행하여 

setup.py에
# nsml: nvcr.io/nvidia/pytorch:20.03-py3
# nsml: nvcr.io/nvidia/pytorch:19.06-py3
# nsml: nvcr.io/nvidia/pytorch:19.07-py3 로 다 해봐도

nsml run -e main_pytorch.py -d 2020KHD_PNS

다음과 같은 메시지와 함께 아예 running하지도 않는 것 같습니다.

<img width="769" alt="스크린샷 2020-09-22 오후 2 27 47" src="https://user-images.githubusercontent.com/6863829/93846757-ecdc7980-fcdf-11ea-890a-8fa248134bb2.png">

빠른  확인 부탁드리겠습니다.

**Comment by taeseug** [comment]
setup.py 파일  첫 라인에서  #nsml: nvcr.io/nvidia/pytorch:20.03-py3 하셨는지 확인 이 필요합니다 . # 은 삭제 하시면 안됩니다.

**Comment by essemfly** [comment]
@taeseug 네  '#' 삭제하지 않았습니다.

**Comment by Hoon8710** [comment]
setup(
    name='ladder_networks',
    version='1.0',
    install_requires=[
        'imbalanced-learn'
    ]
)

또는 
#nsml: nsml/imbalanced-learn 해도 설치가 안되네요

혹시 라이브러리 설치하려면 어떻게 해야하나요?

**Comment by thisisiron** [comment]
저도 같은 문제가 발생합니다. 위의 도커 이미지를 사용하면 `/bin/bash: line 1:   110 Illegal instruction     (core dumped) python -u main.py` 에러가 발생합니다.

 그리고 디폴트로 제공해주신 `#nsml: nsml/default_ml:cuda9_torch1.0` 에서 파이토치 cuda로 실행이 안 됩니다.

**Comment by taeseug** [comment]
@essemfly 
@thisisiron 
@Hoon8710 
setup.py 파일을 올려 주세요

**Comment by essemfly** [comment]
@taeseug 

```
# nsml: nvcr.io/nvidia/pytorch:20.03-py3
from distutils.core import setup
import setuptools

print('setup_test.py is running...')

setup(name='TEAM_NEXT_PYTORCH',
      version='0.1',
      install_requires=['opencv-python']
      )  ## install libraries, 'keras==xx.xx'
```

**Comment by Hoon8710** [comment]
@taeseug 

#nsml: nsml/ml:cuda9.0-cudnn7-tf-1.11torch0.4keras2.2
from distutils.core import setup
import setuptools

print('setup_test.py is running...')

setup(name='PNS_SAMPLE',
      version='1.0',
      install_requires=[
            'matplotlib',
            'tqdm',
            'pillow',
            'scikit-learn',
            'scipy' ,
            'joblib' ,
            'imbalanced-learn'
      ]
      )

**Comment by thisisiron** [comment]
```
#nsml: nvcr.io/nvidia/pytorch:19.07-py3
from distutils.core import setup
import setuptools

setup(
    name='ncc_test',
    version='1.0',
    install_requires=['scikit-learn',
                      'matplotlib',
                      'opencv-python']
)
```

**Comment by taeseug** [comment]
@essemfly  한번 다시 실행 해보시겠습니다. 확인해 보니  KHD050/None/2 session 이 살아 있어 문제가 된것 같습니다,

**Comment by thisisiron** [comment]
@taeseug 
저희 팀은 아직 확인 중인 건가요?

**Comment by taeseug** [comment]
@thisisironsla 팀에서  KHD001/Breast_Pathology/32 session을 실행하고 있는데 맞는지 확인 바랍니다

**Comment by thisisiron** [comment]
@taeseug  

확인이 되기 전까지 일단 디폴트로 설정해주신 도커로 실행 중 입니다. 

문제가 발생한 세션이름은 KHD001/Breast_Pathology/31 입니다. 

세션 종료하고 실행해봐도 될까요?

**Comment by essemfly** [comment]
@taeseug 여전히 똑같은 /bin/bash: line 1: 110 Illegal instruction (core dumped) python -u main.py 에러가 발생합니다.

**Comment by taeseug** [comment]
@thisisiron  우선은 Docker로 돌려 보세요

**Comment by taeseug** [comment]
@essemfly docker를   #nsml: nvcr.io/nvidia/pytorch:20.08-py3 로 변경해 다시 실행해 보세요

**Comment by taeseug** [comment]
@thisisiron님   docker를 #nsml: nvcr.io/nvidia/pytorch:20.08-py3 로 변경해 다시 실행해 보세요

**Comment by taeseug** [comment]
@thisisiron 님도 docker를 #nsml: nvcr.io/nvidia/pytorch:20.08-py3 로 변경해 다시 실행해 보세요

**Comment by essemfly** [comment]
@taeseug Building docker image 에서 20분정도째 막혀있네요. 일단 한번 기다려보겠습니다.

**Comment by thisisiron** [comment]
@taeseug  저도 다시 실행시켰습니다만 세션올리는데 오래 걸려서... 기다려보겠습니다.

**Comment by essemfly** [comment]
@taeseug  네 이제 되는 것 확인했습니다. 감사합니다

**Comment by thisisiron** [comment]
@taeseug 저도 정상적으로 실행됐습니다. 감사합니다!!
