### ISSUE TITLE
track A dataset 질문

### ISSUE THREAD

**Issue by mulkong** [Korea-Health-Datathon/KHD2020#73]
L 또는 R이 모든 이미지에 공통적으로 다 들어가는 건가요? 아니면 어떤 이미지는 L 어떤 이미지는 R만 들어가는 건가요?

**Comment by Leejuhui** [comment]
좌측과 우측 모두 레이블이 0, 1, 2, 3인 경우에만 이용하는 데이터에 포함시킵니다.
따라서, 한 영상에서 양측 모두 이용될 수 있고 한쪽만 이용될 수 있습니다.
예) 00000381_×_2.jpg >> 우측(air-fluid)만 이용
