### ISSUE TITLE
session 할당 관련 요청드립니다.

### ISSUE THREAD

**Issue by Ninebell** [Korea-Health-Datathon/KHD2020#74]
session submit 했다가 ctrl-c로 작업 중단을 시켜 현재 세션 할당도 보이지 않고 gpu 할당도 해제되지 않고있습니다. 

제출한 session은 

submit KHD047/2020KHD_PNS/14 86

으로 제출하였습니다.

**Comment by Korea-Health-Datathon** [comment]
KHD047/2020KHD_PNS/14 세션은 13:28:50에 exit 된 것으로 확인됩니다. 
잠시 기다려보신 후 시도해보시기 바랍니다.

**Comment by Ninebell** [comment]
감사합니다. 
할당이 해제된듯합니다.
