### ISSUE TITLE
gpu limt was exceeded error

### ISSUE THREAD

**Issue by kdh4672** [Korea-Health-Datathon/KHD2020#79]
![gpu_error2](https://user-images.githubusercontent.com/54311546/93853674-3f716200-fcef-11ea-9c6f-a570e0620b3a.png)
![gpu_error1](https://user-images.githubusercontent.com/54311546/93853679-413b2580-fcef-11ea-993e-959f60dd6474.png)

gpu가 팀당 하나로 배정받았다는게 25개팀에 각각 한개가 배정된게 아니라 25팀이 25개의 gpu를 공유하는건가요?
계속 시도하는데 gpu가 이미 쓰이고 있는것 같아서 실행이 안되네요.

**Comment by Korea-Health-Datathon** [comment]
아래 명령어로 KHD050/None/2 세션을 삭제하고 실행해보시기 바랍니다.
 
nsml rm -f KHD050/None/2
