### ISSUE TITLE
B track score에 관하여 질문

### ISSUE THREAD

**Issue by jhkjhkim** [Korea-Health-Datathon/KHD2020#81]
안녕하세요 32조 '장어탕가디언' 입니다.

다름이 아니라, 모델을 학습시킨 후 submit을 했을 때, 어떤 모델을 사용해도 계속 0.4가 나오는 현상을 겪고있습니다. 

이에 대해서 여쭤보고 싶습니다. 감사합니다.

**Comment by Korea-Health-Datathon** [comment]
모델이 병리 데이터를 제대로 학습하지 못하는 것으로 보여집니다.

테스터팀(khdadmin)에서 모델을 수정하여 확인한 결과, 점수가 0.4 -> 0.8951로 상승하였습니다.
배포된 코드 및 validation에는 이상이 없습니다.

![image](https://user-images.githubusercontent.com/70007451/93946736-04b20d00-fd75-11ea-8c2a-40d7b4a46858.png)

![image](https://user-images.githubusercontent.com/70007451/93946746-0b408480-fd75-11ea-9ce9-b4fa427e3955.png)

**Comment by nccaiteam** [comment]
추가적으로 코멘트를 드리면, 기본적으로 제공되는 모델을 사용하기 보다는 널리 알려진 모델들을 활용하시면 성능이 향상 됨을 확인하실 수 있을 것입니다.
