### ISSUE TITLE
[B track] 샘플이미지 문의드립니다.

### ISSUE THREAD

**Issue by IllgamhoDuck** [Korea-Health-Datathon/KHD2020#82]
B track 부비동 각 클래스별 샘플이미지를 제공해주실 수 없나요?

**Comment by Leejuhui** [comment]
안녕하세요. 
부비동 샘플 영상은 제공이 어렵습니다.
모든 Water's view radiograph는 구글 검색 결과 이미지들과 거의 흡사합니다.
구글 검색과 데이터 설명 자료 ppt를 참고해주시면 좋을 것 같습니다.

**Comment by Leejuhui** [comment]
추가로, 부비동은 A 트랙임을 말씀 드립니다 :)
