### ISSUE TITLE
[B 트랙] 스코어 0.4만 나오는 현상

### ISSUE THREAD

**Issue by suheey** [Korea-Health-Datathon/KHD2020#84]
현재 keras 기반 여러가지 모델로 변경하여 학습하고, 테스트 결과 값 확인하였더니
제공해주신 CNN baseline 모델을 포함하여 모든 모델의 테스트 결과가 0.4가 나오고 있습니다.

또한, torch baseline model, keras baseline model 두 경우 모두
코드의 dropout rate만 수정하는 최소한의 수정을 하였는데도 계속해서 0.4가 나왔습니다.

모델이 바뀌고, keras/torch 두 파일 모두 0.4가 나온다는 것은 배포해주신 코드 혹으느 test performance 계산 값 혹은 제출 코드의 issue가 있는 것은 아닌가요?

빠른 답변 부탁드립니다.

**Comment by Korea-Health-Datathon** [comment]
베이스라인 코드 및 validation에는 이상이 없습니다.
#81 참고 부탁드립니다.

**Comment by nccaiteam** [comment]
추가적으로 코멘트를 드리면, 기본적으로 제공되는 모델을 사용하기 보다는 널리 알려진 모델들을 활용하시면 성능이 향상 됨을 확인하실 수 있을 것입니다.

**Comment by suheey** [comment]
널리 알려진 Resnet, Xception, Inception 다 썼지만 그대로 0.4가 나옵니다. 학습된 모델이 테스트 타임에 사용되는 것이 아닌, 학습이 한번도 안된 모델이 테스트에 쓰이는 것 같아, 모델 웨이트 저장 혹은 테스트 타임때 불러오는 코드가 잘 못 되지 않았나 싶습니다..

**Comment by MiSeon23** [comment]
@suheey 혹시 어떻게 해결하셨는지 여쭤봐도 될까요?

**Comment by suheey** [comment]
저희는 모델의 아웃풋 레이어 노드 수를 조정했습니다.
