### ISSUE TITLE
session 할당 관련 문의

### ISSUE THREAD

**Issue by mulkong** [Korea-Health-Datathon/KHD2020#85]
코드를 Submit할 때, 디버깅을 하고 싶어  allocation 때문에 한시간 마다 확인을 하고 있습니다. 혹시 디버깅만을 위한 목적으로 바로바로 확인하는 방법은 없나요?

**Comment by Korea-Health-Datathon** [comment]
[sli.do를 통해 이미 답변 드렸습니다만 참고를 위해 이 곳에도 내용을 남기도록 하겠습니다]

issue #50 답변을 참고해서, 이미 한 번 building 된 적 있었던 docker image를 사용하는 경우, docker image가 1분 안에 building 되지 않으면 해당 세션을 nsml rm -f session_id 로 삭제하고, 새롭게 run을 돌리길 반복하다보면 빠르게 building 되는 케이스를 찾을 수 있다 합니다. 1분이내 빌드가 안되는 경우 세션을 바로 삭제후 다시 시도 부탁드려요
