### ISSUE TITLE
[A트랙] Test dataloader 관련

### ISSUE THREAD

**Issue by ChoiDM** [Korea-Health-Datathon/KHD2020#88]
안녕하세요, TAIL팀입니다.

혹시 test dataset을 위한 data loader는 evaluation/data_loader.py로 고정이며 custom data loader는 사용할 수 없는 것일까요?

**Comment by Leejuhui** [comment]
안녕하세요. 
LoadTestData 함수는 고정입니다.
모델 입력 전 preprocessing이 필요할 경우
main_*.py 에서 model_bind.infer 함수를 통해 수정 가능한 부분은 있습니다.
