### ISSUE TITLE
[A트랙] [보라카이팀] 부비동 이미지 레이블 매핑 확인 요청

### ISSUE THREAD

**Issue by d4rk6un** [Korea-Health-Datathon/KHD2020#90]
안녕하세요. 보라카이팀 김광열입니다.

지난 9/21(월) 본식 부비동 데이터 설명 세션([KHD_2020_PNS.pdf](https://github.com/Korea-Health-Datathon/KHD2020/files/5262881/KHD_2020_PNS.pdf))에서 아래와 같이 이미지의 좌측 영역이 환자의 우측 상악동을 의미하고, 파일명에서 좌상악동 레이블 다음에 우상악동 레이블이 나오는 것으로 이해했습니다.

![image](https://user-images.githubusercontent.com/3839602/93912472-c7cb2380-fd3e-11ea-80cc-01ad008a25c5.png)

![image](https://user-images.githubusercontent.com/3839602/93912413-b71aad80-fd3e-11ea-9b84-b38ea0a19d9c.png)

python code를 보면 이미지의 왼쪽 부분(우측 상악동)을 파일명의 앞쪽 레이블(좌상악동 레이블)로 매핑하고 있습니다.
혹시 원래 의도하신대로 레이블링이 제대로 매핑이 된 것인지 확인 부탁 드립니다.

1. 저희가 개발중인 모델로 학습할 경우 좌/우 레이블링을 교환할 경우 val_acc가 더 좋아지는 경우가 있음.
2. 모든 참가팀의 leaderboard score가 전체적으로 좋지 않은 것으로 보임.

submit 단계에서는 자동으로 generator되는 evaluation/data_loader.py 에서 data load되어 데이터 변경이 불가능하여 참가 팀이 직접 확인이 어려워 문의 드립니다.

감사합니다.

**Comment by Leejuhui** [comment]
안녕하세요.
데이터가 있는 사무실에서 확인 후 공지 드리도록 하겠습니다.
감사합니다.

**Comment by gusdkgusdk** [comment]
안녕하세요.

레이블 매핑에는 문제가 없는 것으로 확인됐습니다.
감사합니다.

**Comment by Jwill1994** [comment]
보라카이팀에서 말씀하신대로 좌측 이미지가 우측 레이블에 매핑하는거 자체가 문제없다고 말씀하신거맞나요?

**Comment by gusdkgusdk** [comment]
네, 맞습니다.

화면상 좌측 이미지가 우측 레이블로 매핑이 되어있습니다.

**Comment by Jwill1994** [comment]
아죄송합니다. 질문을 잘못드렸네요. 보라카이팀에선 문의주시기를 좌이미지가 앞쪽(좌)레이블로 매핑되었다고 문의주셔서 그걸 여쭤보려했습니다.

**Comment by gusdkgusdk** [comment]
좌측이미지가 뒷쪽(우)레이블로 매핑되어 있습니다.

00015201_0_**1**.jpg

**Comment by gusdkgusdk** [comment]
안녕하세요, 건양대병원입니다.

문의주신 글들 기반으로 검토한 결과 데이터 자체에 레이블 매핑은 문제가 없는 것으로 확인됐습니다.

다만, main 및 평가 코드에서 좌/우 레이블 로드에 오류가 있어 다시 업로드를 했습니다.

DataLoad 함수에서 변경된 부분 아래에 첨부하니 수정해서 진행 부탁드립니다.
https://github.com/KYBiMIL/KHD_2020/blob/master/tf_keras/main_keras.py

l_img = img_whole[:, w_:2*w_]
r_img = img_whole[:, :w_]

재차 확인을 했어야 하는데, 죄송합니다.

감사합니다.

**Comment by d4rk6un** [comment]
아래 정정해주신 내용이 본 이슈에서 말씀드린 레이블링 오매핑 현상이 맞습니다.

결국 정정 전까지는 이미지의 좌우측이 반대의 레이블이 매핑된 것으로 보이네요.

빠른 확인 해주셔서 감사드립니다.

l_img = img_whole[:, w_:2*w_]
r_img = img_whole[:, :w_]
