### ISSUE TITLE
nsml sign in이 되지 않습니다.

### ISSUE THREAD

**Issue by MHYNW** [Korea-Health-Datathon/KHD2020#95]
얼룩말팀의 임현우입니다.
다른 팀원은 정상적으로 로그인이 되나 제 계정으로는 nsml에 로그인을 할 수 없어 문의드립니다.
github 아이디가  MHYNW 이고요.
You are not a registered user. Please contact the administrator. ( dl_nsml_alpha@navercorp.com )  라고 계속 화면에 떠서 문의드립니다.

**Comment by Korea-Health-Datathon** [comment]
해당 ID는 정상적으로 등록되어 있는 상태입니다.
![image](https://user-images.githubusercontent.com/70007451/93960596-574ef180-fd94-11ea-800f-d4f0a9904fe4.png)

로그인 전체 화면을 한번 캡쳐해서 보여주실 수 있으실까요?

**Comment by MHYNW** [comment]
아 이제 되네요 감사합니다

**Comment by Korea-Health-Datathon** [comment]
넵. 이슈 클로징 하도록 하겠습니다.
