### ISSUE TITLE
Submission error 

### ISSUE THREAD

**Issue by kyuheejo** [Korea-Health-Datathon/KHD2020#96]
현재 GPU 를 사용하고 있는 세션이 없음에도 Submit을 하면 다음과 같은 에러가 뜹니다. 
<img width="649" alt="submission error" src="https://user-images.githubusercontent.com/21049855/93970781-bb2fe500-fda9-11ea-8c86-23a0127a16cb.png">

**Comment by Korea-Health-Datathon** [comment]
KHD023/2020KHD_PNS/126 세션이 allocating 중인 것으로 뜨고 있는데 혹시 방금 submit하신건가요?

**Comment by kyuheejo** [comment]
submit 하는 중에 결과가 나오지 않고 멈춰서 (?) exit 한것으로 알고 있습니다. 다른 코드를 run 해도 똑같이 GPU limit 이 exceeded 되었다는 에러가 떠서 아무것도 못하고 있습니다. 도움 주시면 감사하겠습니다.

**Comment by kyuheejo** [comment]
session 126 rm 하였더니 해결되었습니다 감사합니다

**Comment by Korea-Health-Datathon** [comment]
답변 쓰는 중에 완료되었군요. :)
본 이슈는 클로징 하겠습니다.
