### ISSUE TITLE
베이스라인-디버깅용 데이터도 얼로케이팅이 안되고 다음과 같은 오류 메세지가 뜹니다.

### ISSUE THREAD

**Issue by seoha-kim** [Korea-Health-Datathon/KHD2020#99]
Sessions not found: KHD033/PNS5/119
Usage: nsml logs [OPTIONS] SESSION

Error: Invalid value for "SESSION": No valid sessions

**Comment by siksimi** [comment]
안녕하세요
저도 같은 문제가 있었는데,, 제 경우에는 setup.py 문법오류였습니다.
